program_auto_enrolment_properties_url: "https://raw.githubusercontent.com/Possiblehealth/possible-config/master/properties/programautoenrolment.properties"
program_auto_enrolment_omod_url: "https://github.com/Possiblehealth/program-auto-enrollment/releases/download/1.0.1/programautoenrolment-1.0-SNAPSHOT.omod"
bahmniapps_url: "https://s3.ap-south-1.amazonaws.com/possible-artifacts/bahmniapps.zip"
bahmni_user: bahmni
bahmni_group: bahmni
bahmni_mrs_temp_files:
  - bahmniapps.zip
