program_auto_enrolment_properties_url: "https://raw.githubusercontent.com/Possiblehealth/possible-config/release-0.84/properties/programautoenrolment.properties"
program_auto_enrolment_omod_url: "https://github.com/Possiblehealth/program-auto-enrollment/releases/download/1.0.1/programautoenrolment-1.0-SNAPSHOT.omod"
bahmni_user: bahmni
bahmni_group: bahmni