- name: Stop bahmni-lab
  service:
    name=bahmni-lab
    state=stopped
  when: passive is not defined or passive != 'yes'

- name: Get bahmni-lab from remote location if configured
  get_url: url={{ bahmnilab_url }}
   force=yes
   dest=/opt/bahmni-web/etc/bahmni-lab.zip
   mode=0755
  when: bahmnilab_url is defined

- name: Removing Possible files from bahmni-lab
  file:
      path=/opt/bahmni-lab/bahmni-lab/{{item}}
      state=absent
  with_items:
      - "{{ possible_lab }}"

- name: Unzip downloaded bahmni-lab file
  command: unzip /opt/bahmni-web/etc/bahmni-lab.zip -d /opt/bahmni-web/etc/possible-bahmni-lab
  when: bahmnilab_url is defined

- name: copying from /var/www/bahmni-lab to Possible bahmni-lab
  command: cp -r /opt/bahmni-web/etc/possible-bahmni-lab/OpenElis/{{item}} /opt/bahmni-lab/bahmni-lab/
  with_items: "{{ possible_lab }}"

- name: Removing temporary files from bahmni-lab
  file:
      path=/opt/bahmni-web/etc/{{item}}
      state=absent
  with_items:
      - "{{ bahmni_lab_temp_files }}"

- name: Start bahmni-lab
  service:
    name=bahmni-lab
    state=started
  when: passive is not defined or passive != 'yes'